grafana-dashboard:
    image: samsaffron/graphite
    ports:
        - "9090:80"
        - "8080:3000"

dropwizard-metrics:
    build: .
    links:
        - grafana-dashboard
    command: ["java", "-Dgraphite.enabled=true", "-Dscheduledtasks.addremoveanimals.fixedRate=2300", "-Dlogging.level.net.eekie.metrics=INFO", "-jar", "/metrics/dropwizard-metrics-1.0-SNAPSHOT.jar"]
    ports:
        - "9875:9875"

