version: '2'
services:
    grafana-dashboard:
        image: samsaffron/graphite
        ports:
            - "9090:80"
            - "8080:3000"

    dropwizard-metrics:
        image: eekie/dropwizard-metrics
        links:
            - grafana-dashboard
        command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-XX:-UsePerfData", "-Dgraphite.enabled=true", "-Dscheduledtasks.addremoveanimals.fixedRate=2300", "-Dlogging.level.net.eekie.metrics=INFO", "-jar", "/metrics/app.jar"]
        ports:
            - "9875:9875"

